### ISSUE TITLE
Lag action som automatisk legger nye issues i behov-repo til Behovsprosjektet

### ISSUE THREAD

**Issue by stigbd** [behandlingsoversikt/issue-tracker#1]
For tilsvarande action, sjå 
https://github.com/Informasjonsforvaltning/behov/blob/master/.github/workflows/add_issue_to_project.yaml

- [ ] Lag action
- [ ] Opprett org secret basert på en PAT

**Comment by valosnah** [comment]
Skal stenges ned, kan trygt lukkes
