### ISSUE TITLE
Feil - Rapport "Protokoll CSV og HTML blir generert selv om "felles" obligatoriske felt ikke er utfylt

### ISSUE THREAD

**Issue by RogerSOlsen** [behandlingsoversikt/issue-tracker#10]
**Feil:**
Det er mulig nå å generere rapport "Protokoll" (HTML) og "Protokoll CSV" uten at alle "felles" obligatoriske felt er utfylt. Dette skal ikke være mulig. 

**Beskrivelse av funksjonalitet for generering av rapport Protokoll slik den er ment å fungere**
Krav til innhold i Protokoll over behandlingsaktiviteter er beskrevet i Lov om behandling av personopplysninger artikkel 30 (https://lovdata.no/dokument/NL/lov/2018-06-15-38/KAPITTEL_gdpr-4-1#gdpr/a30 ). Kravene i artikkel 30 er merket "Obligatorisk"  i løsningen Behandlingsoversikt. 

Noen av kravene til innhold i protokoll er informasjon som skal oppgis  - og som er lik, og derved gjentagende, for alle virksomhetens behandlingsaktiviteter. Vi har organisert løsningen Behandlingsoversikt slik at informasjon som gjelder for alle virksomhetens behandlingsaktiviteter, for eksempel navn på Personvernombud, fylles ut kun en gang.  
Her er en oversikt over tema som er felles for alle virksomhetens behandlingsaktiviteter, og som derfor kun skal registreres en gang i Behandlingsoversikt. Merk at alle feltene er obligatoriske og skal fylles ut: 

![image](https://user-images.githubusercontent.com/32771488/190641167-4752384b-b362-4643-9201-7a271e911063.png)

Temaet "Er behandlingsansvarlig etablert utenfor EU/EØS" har default verdi "Nei". 
Dersom virksomhetens behandlingansvarlig er etablert utenfor EU/EØS, må man klikke på Ja. Da skal også feltene som da blir synlige, fylles ut:
![image](https://user-images.githubusercontent.com/32771488/190641960-1bf3726d-f6dc-4e90-aa96-9817b8b17492.png)

Samtlige felt under overskriftene "Behandlingsansvarlig" og "Personvernombud" skal fylles ut. Informasjon i feltene skal vises øverst i rapport "Protokoll (HTML) samt i de første kolonnene i rapport "Protokoll CSV".

Dersom man har svart Nei på "Er behandlingsansvarlig etablert utenfor EU/EØS", skal ikke overskriften "Representant for behandlingsansvarlig", tittel på feltene samt verdi Nei vises i rapport "Protokoll (HTML). I rapport "Protokoll CSV" skal overskriftene vises, men feltene skal ikke ha noen verdi. 
Dersom man har svart Ja på "Er behandlingsansvarlig etablert utenfor EU/EØS", skal overskriften "Representant for behandlingsansvarlig", tittel på feltene, og verdi som er fylt ut  i feltene,  vises i rapport "Protokoll (HTML). I rapport "Protokoll CSV" skal overskrifter vises. og feltene ha verdi.

**Comment by jeffreiffers** [comment]
Denne kan testes i staging.

**Comment by RogerSOlsen** [comment]
Test i staging på virksomhet "Liland og Erland revisjon". Dette er en virksomhet hvor utfylling av alle testede felter var påbegynt da jeg startet testing. Merk at jeg derfor ikke har testet vet hvordan endringer vil opptre dersom jeg var den første som gikk inn i behandlingsoversikt til en virksomhet og startet med tomme felt.

Startet med verdier i alle felter under "Behandlingsansvarlig", "Personvernombud" og "Representant for behandlingsansvarlig". Det var da mulig å generere rapport "Protokoll" og "Protokoll CSV". 

Informasjon ble deretter fjernet i ett felt i gangen i hver bolk. Når felt ble tømt, kom melding "Ett eller flere obligatoriske felt er ikke fylt ut. For å generere rapporter for protokoll må disse fylles ut.". Valgene "Protokoll" og "Protokoll CSV" blir da lys grå og er ikke mulig å aktivere. 
Når det blir lagt inn tekst igjen i tomme felt, blir valgene "Protokoll" og "Protokoll CSV" aktive igjen. 
Feltene "e-post" gjør valg på "Protokoll" og "Protokoll CSV" inaktiv dersom epostadresse har punktum etter alfakrøll, eller dersom epostadresse mangler domene extension.
**Test OK!**
Kommentar: hvis det er mulig, hadde det væt fint med kontroll på at det ligger telefonnummer i telefonfeltet i stedet for at det nå tillates alfanumerisk verdi

**Comment by jeffreiffers** [comment]
Tenker du følgende format på telefonnummer "+0-9"? Skal vi tillate mellomrom?

**Comment by RogerSOlsen** [comment]
ja, vi bør tillate + i telefonnummerfeltet. Jeg kan lite om hva som er vanlig praksis, men tenker det bør være tillatt å ha mellom dersom det er vanlig
