### ISSUE TITLE
Feil  i  Behandlingsoversikt ved søk på datasettbeskrivelser

### ISSUE THREAD

**Issue by RogerSOlsen** [behandlingsoversikt/issue-tracker#12]
det er ikke mulig å søke på datasettbeskrivelser i demo-miljøet. Dette ser ut til å virke greit i produksjon. 

Oppdatert problembeskrivelse: 
Kan tyde på at det er en feil spesifikt knyttet til Rogers bruker og/eller demo-organisasjonen Høgskolen for IT og arktikektur.

Problembeskrivelse:

-  jeg ønsker å kople datasettbeskrivelsen "API-katalog i Felles datakatalog", som er publisert i demo-portal under virksomhet "Høgskolen for it og arkitektur" (https://demo.fellesdatakatalog.digdir.no/datasets/0fc9c122-c17f-3957-bfdd-55eed9da9d05 ) til en behandlingsaktivitet under samme virksomhet
- logger inn i demo registreringsløsning på virksomhet "Høgskolen for IT og arkitektur" (org. nummer 555111290)
- prøver å søke opp navnet på datasettbeskrivelsen i feltet "Tilhørende datasett" ved å skrive inn navnet på datasettbeskrivelsen, men får ikke skrevet noe i feltet. Til høyre i registreringsfeltet står det et hjul og spinner (NB! I behandlingsaktiviteten som dette skjermbildet er tatt fra, lå det det to datasettbeskrivelser fra før ("tull og tøys" og "Regnskapsregisteret jme", men jeg får samme feil når jeg prøver å knytte en datasettbeskrivelse til en helt ny behandlingsaktivitet som det ikke er registrert noe i tidligere:

![image](https://user-images.githubusercontent.com/32771488/216610928-8952eb08-1692-49a3-943f-94489014bce8.png)

I produksjon virker dette greit. Eksempel: 

- jeg ønsker å knytte datasettbeskrivelsen "Kontrollert vokabular Regeltype" (https://data.norge.no/datasets/36f1732e-abae-3512-9978-bc382c7bc2cb) som Digdir står som eier til, til en ny behandlingsaktivitet. 
- åpner en ny behandlingsaktivitet i produksjon under Digdir
- starter på å skrive"Kontrollert vokabular Regeltype" i søkefeltet 
- allerede på første bokstav "K" vises flere treff. Jeg antar at dette er treff som har bokstaven "K" et sted i navnet på datasettbeskrivelsen, men listen over treff viser foreløpig ikke den datasettbeskrivelsen jeg ønsker å kople til behandlingsaktiviteten:
![image](https://user-images.githubusercontent.com/32771488/235648226-4d56a5b8-3c68-41f0-943c-3763d703f683.png)
Etter hvert som jeg skriver flere bokstaver får jeg færre valgmuligheter. Til slutt vises den datasettbeskrivelsen jeg vil kople til Behandlingsaktiviteten i listen over alternativer:
![image](https://user-images.githubusercontent.com/32771488/235652298-8f5d5d00-9759-4410-b4ef-655cf1ae7780.png)

Jeg kan da klikke på navnet "Kontrollert vokabular Regeltype". Navnet på datasettbeskrivelsen legges da inn som en "tag" under søkefeltet: 
![image](https://user-images.githubusercontent.com/32771488/235652957-655cb563-fea0-4db1-8f92-b2af77ce3163.png)

Jeg kan legge til flere datasettbeskrivelser om jeg ønsker det: 
![image](https://user-images.githubusercontent.com/32771488/235653182-bd807dde-c05c-4c03-95b1-19874521fc64.png)

Dersom jeg kopierer navnet på datasettbeskrivelsen fra portalen og limer den inn i søkefeltet, får jeg vist datasettbeskrivelsen jeg leter etter med en gang (og kun den): 
![image](https://user-images.githubusercontent.com/32771488/235650860-f55f5b1f-aeef-4fc7-976f-a3c2f1a48d10.png)

**Comment by terjesyl** [comment]
Er det meningen at man skal kunne lenke til datasett som eies/er publisert av andre virksomheter enn den man representer i Behandlingsoversikt?
@KjerstiSteien @RogerSOlsen 
Uten å sjekket for nøye mistenker jeg at det er noen begrensninger på det nå, hos meg funker nemlig søkeforslag i demo.

**Comment by jeffreiffers** [comment]
Det fungerer fint hos meg også. Kan jeg lukke saken @RogerSOlsen ?

**Comment by terjesyl** [comment]
@jeffreiffers Testet med Roger nå, ser at feltet fryser/blokkerer på spinneren når vi gjør søk opp mot et datasett eid av Høgskolen for IT og arkitektur (som Roger er logget inn på vegne av). Vi forventer med andre ord at søket skal fungere der. Usikker på hva feil kan være, trenger noen kyndige til å se på det:)

**Comment by terjesyl** [comment]
Roger testet også søk når han var logget inn som Michelle Westlie, der fungerte det. Så kan tyde på at det er en feil spesifikt knyttet til Rogers bruker og/eller demo-organisasjonen Høgskolen for IT og arktikektur.

**Comment by jeffreiffers** [comment]
Teoretisk skal det ikke bety noe hvilken bruker som er logget på. Vi får sette opp et møte.

**Comment by KjerstiSteien** [comment]
Lukker denne saken, og åpner den heller igjen om vi får tilsvarende meldinger fra brukere. Hvis vi ikke har brukere med dette problemet, bør vi ikke bruke for mye tid på dette, siden løsningen skal legges ned.
