### ISSUE TITLE
Registrering: Logges ikke helt ut av løsningen når man trykker på Logg ut

### ISSUE THREAD

**Issue by AinaEngen** [behandlingsoversikt/issue-tracker#6]
Testet i publiseringsløsningen
Logger inn med ID-porten
Trykker på "Logg ut" og kommer tilbake til innloggingssiden.
Trykker på innlogging ID-porten igjen, brukeren er fortsatt innlogget

**Comment by AinaEngen** [comment]
Feilregistrert

**Comment by AinaEngen** [comment]
@NilsOveTen - registrerte bug som avtalt i standup, men får ikke lov til å sette labels eller assigne til noen. Har jeg gjort noe feil? Lagt den på feil område eller noe?

**Comment by NilsOveTen** [comment]
> @NilsOveTen - registrerte bug som avtalt i standup, men får ikke lov til å sette labels eller assigne til noen. Har jeg gjort noe feil? Lagt den på feil område eller noe?

Sikkert fordi du ikke er lagt til i behandlingsoversikt, eller hur @valosnah?

**Comment by NilsOveTen** [comment]
Vi fant vel uansett ut at det ikke var et problem for behandlingsoversikt, bare registrering-portal og dataset-catalog-gui, lukker denne.

**Comment by NilsOveTen** [comment]
løses av https://github.com/Informasjonsforvaltning/registration-portal/issues/80
